# PRAUTO lifecycle labels
- name: "prauto:ready"
  color: "0E8A16"
  description: "Ready for PRAUTO to pick up"

- name: "prauto:wip"
  color: "FBCA04"
  description: "PRAUTO is working on this issue"

- name: "prauto:review"
  color: "1D76DB"
  description: "PRAUTO PR is ready for human review"

- name: "prauto:failed"
  color: "D93F0B"
  description: "PRAUTO abandoned after max retries"

- name: "prauto:done"
  color: "6F42C1"
  description: "PRAUTO work completed — squash-pushed and ready to merge"
