# PRAUTO lifecycle labels
- name: "prauto:ready"
  color: "85E89D"
  description: "Ready for PRAUTO to pick up"

- name: "prauto:wip"
  color: "FBCA04"
  description: "PRAUTO is working on this issue"

- name: "prauto:review"
  color: "1D76DB"
  description: "PRAUTO PR is in review"

- name: "prauto:failed"
  color: "D93F0B"
  description: "PRAUTO abandoned after max retries"

- name: "prauto:done"
  color: "006400"
  description: "PRAUTO PR is approved and ready to be merged"
