name: PRAUTO Task
description: Create a task for the PRAUTO autonomous worker
labels: ["prauto:ready"]
body:
  - type: markdown
    attributes:
      value: |
        - PRAUTO will pick up this issue automatically. Provide as much structured context as possible for better results.
        - If the issue is not fully specced yet, remove the `prauto:ready` label and re-add it when ready.

  - type: checkboxes
    id: spec-scope
    attributes:
      label: Spec Scope
      description: Which parts of the specification are affected?
      options:
        - label: Architecture or high-level spec (spec/)
        - label: Cross-role feature spec (spec/feature/)
        - label: Role-specific feature spec (spec/feature/spoke/)
        - label: Tooling or CI/CD (PRAUTO, GitHub Actions, hooks, etc.)
        - label: No spec change (implementation only)
        - label: Other (documented in description)

  - type: checkboxes
    id: impl-scope
    attributes:
      label: Implementation Scope
      description: Which parts of the implementation are affected?
      options:
        - label: OpenAPI spec (api/)
        - label: Backend - API routes and services
        - label: Backend - Temporal workflows
        - label: Backend - DataHub integration, PostgreSQL models, Qdrant vector search
        - label: Frontend UI
        - label: Helm charts / Kubernetes manifests
        - label: Dev environment
        - label: Tooling or CI/CD (PRAUTO, GitHub Actions, hooks, etc.)
        - label: No impl change (spec only)
        - label: Other (documented in description)

  - type: dropdown
    id: change-size
    attributes:
      label: Change Size
      description: Estimated size of the change, counting both spec and implementation
      options:
        - Minor (single file or a few files)
        - Medium (multiple files across a few directories)
        - Major (many files across multiple directories)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What needs to be done?
      value: |
        ### Background
        <!-- Why is this change needed? -->

        ### Spec
        <!-- Key requirements or constraints -->

        ### TODO
        - [ ]
    validations:
      required: true

  - type: textarea
    id: spec-refs
    attributes:
      label: Spec References
      description: Which spec files are relevant?
      placeholder: |
        e.g.
        - spec/feature/API.md (section: Health Check)
        - spec/ARCHITECTURE.md (section: Three-tier routing)

  - type: textarea
    id: file-paths
    attributes:
      label: File Paths (if known)
      description: Files to create or modify
      placeholder: |
        e.g.
        - src/api/routes/health.py (create)
        - src/api/main.py (modify)

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: How do we know this is done?
      placeholder: |
        - [ ] Endpoint returns 200 with expected payload
        - [ ] Unit tests pass
        - [ ] Follows API design principles
